import seedData from './data/seed-anime.json'
import { createAnime, emptyCriteria, type Anime, type CriterionScores } from './types'

/**
 * The list extracted from N.xlsx, bundled with the app.
 *
 * Generated by scripts/build-seed.mjs: the sheet scores each criterion out of
 * 20 and the app scores out of 100, so values are multiplied by 5. AniList
 * supplies the real title, year, studio, cover image and genres.
 */
export interface SeedEntry {
  sheetLabel: string
  title: string
  englishTitle: string | null
  year: number | null
  studio: string | null
  format: string | null
  totalEpisodes: number | null
  coverImage: string | null
  genres: string[]
  anilistId: number
  malId: number | null
  siteUrl: string | null
  criteria: Partial<CriterionScores>
  sheetTotal: number | null
  favouriteCharacter: string | null
  favouriteOst: string | null
  favouriteOpening: string | null
  favouriteEpisode: string | null
}

interface SeedFile {
  version: number
  source: string
  generatedAt: string
  count: number
  anime: SeedEntry[]
}

const seed = seedData as unknown as SeedFile

export function seedCount(): number {
  return seed.anime.length
}

export function seedGeneratedAt(): string {
  return seed.generatedAt
}

/** Loose title key used to detect an anime that is already in the library. */
function titleKey(title: string): string {
  return title
    .toLowerCase()
    .normalize('NFKD')
    .replace(/[\u0300-\u036f]/g, '')
    .replace(/[^a-z0-9]+/g, '')
}

function entryToAnime(entry: SeedEntry): Anime {
  const criteria = emptyCriteria()
  for (const [key, value] of Object.entries(entry.criteria)) {
    if (typeof value === 'number' && Number.isFinite(value) && key in criteria) {
      criteria[key as keyof CriterionScores] = value
    }
  }

  // The sheet's "favourites" columns are worth keeping, so they become notes.
  const notes = [
    entry.favouriteEpisode && `Favourite episode: ${entry.favouriteEpisode}`,
    entry.favouriteCharacter && `Favourite character: ${entry.favouriteCharacter}`,
    entry.favouriteOst && `Favourite OST: ${entry.favouriteOst}`,
    entry.favouriteOpening && `Favourite opening: ${entry.favouriteOpening}`,
    entry.sheetLabel !== entry.title && `Listed as "${entry.sheetLabel}" in the sheet`
  ]
    .filter(Boolean)
    .join('\n')

  return createAnime({
    title: entry.title,
    englishTitle: entry.englishTitle ?? undefined,
    year: entry.year ?? undefined,
    studio: entry.studio ?? undefined,
    status: 'completed',
    criteria,
    totalEpisodes: entry.totalEpisodes ?? undefined,
    coverImage: entry.coverImage ?? undefined,
    genres: entry.genres.length > 0 ? entry.genres : undefined,
    notes: notes || undefined,
    source:
      entry.anilistId > 0
        ? {
            provider: 'anilist',
            anilistId: entry.anilistId,
            malId: entry.malId,
            siteUrl: entry.siteUrl ?? `https://anilist.co/anime/${entry.anilistId}`
          }
        : undefined
  })
}

export interface SeedImportResult {
  added: Anime[]
  /** Titles already present, left untouched. */
  skipped: string[]
}

/**
 * Merge the bundled list into the library.
 *
 * Entries already present (matched on a normalised title) are skipped rather
 * than overwritten, so importing twice is harmless and any rating you have
 * added yourself survives.
 */
export function buildSeedImport(existing: Anime[]): SeedImportResult {
  const known = new Set<string>()
  for (const anime of existing) {
    known.add(titleKey(anime.title))
    if (anime.englishTitle) known.add(titleKey(anime.englishTitle))
  }

  const added: Anime[] = []
  const skipped: string[] = []

  for (const entry of seed.anime) {
    const keys = [titleKey(entry.title), entry.englishTitle ? titleKey(entry.englishTitle) : null]
    if (keys.some((k) => k && known.has(k))) {
      skipped.push(entry.title)
      continue
    }
    const anime = entryToAnime(entry)
    added.push(anime)
    known.add(titleKey(anime.title))
  }

  return { added, skipped }
}

export function seedSource(): string {
  return seed.source
}
